language: java

sudo: false

script: mvn verify -Pintegration

branches:
  only:
    - master

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

after_success:
  - mvn clean cobertura:cobertura coveralls:report -Pintegration
